name: Sync multiple branches
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
          